#!/usr/bin/env bash
#
# This wizard gives a manual procedure one step at a time.
# Generated by the /wizard skill.
#
# The code above the "STAGES" marker comes from the wizard skill.
# Repository language rules apply to the generated text.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Set these two values at the start of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # Actions that the wizard could not do.

# Clear the terminal so that it shows only the current step.
# Do not clear output that is not in a terminal.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# Show the wizard purpose and estimated duration.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  # Tell the user what to do in the browser and store the values that the user enters.
  printf '%s  Follow the browser instructions and enter the requested values.\n' "$DIM"
  printf '  To stop, press Ctrl-C. You can start the wizard again later.\n'
  printf '  The wizard keeps the values that it already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# Clear the screen and show the stage, progress, and remaining time.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# Show an instruction.
say()  { printf '  %s\n' "$1"; }
# Show an action that the user must do.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# Open a URL in the user's browser. Support macOS, Linux, and WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "The wizard could not open a browser. Open this URL: $url"; fi
  } >/dev/null 2>&1 || warn "The wizard could not open a browser. Open this URL: $url"
}

# Wait until the user confirms that the manual action is complete.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# Ask a yes-or-no question. Return success for yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# Get the current KEY value from ENV_FILE.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# Read a visible value into KEY. Enter keeps an existing value.
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# Read a hidden value into KEY. Enter keeps an existing value.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# Write KEY=VALUE to ENV_FILE. Replace an existing KEY value.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# Set a GitHub Actions secret. Record a warning if gh is not ready.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "The wizard did not set GitHub secret $name. Set it later."
}

# Set a GitHub Actions variable that is not a secret.
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "The wizard did not set GitHub variable $name. Set it later."
}

# Clear the screen and show a configuration summary.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "The wizard wrote these environment values to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "The wizard set these GitHub secrets: ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "Complete these actions manually:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES. Add one stage() call for each group of user actions.
# Make the total values agree with the stages.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=17
TOTAL_MINUTES=61
ENV_FILE="${DOUBTFIRE_ENV_FILE:-.env.local}"

banner "Doubtfire private deployment"

stage "Clerk development application" 3
say "Create the Clerk application for local development."
open_url "https://dashboard.clerk.com/apps/new"
step "Create an application named Doubtfire."
step "If Clerk shows a framework guide, close it. The app already contains the Clerk code."
pause "Continue when the Doubtfire development application exists."

stage "Clerk development sign-in" 4
say "Enable the identifiers and password for the predefined account."
open_url "https://dashboard.clerk.com/"
step "Open Configure, then User & authentication."
step "On Email, enable Sign-up with email and Sign-in with email."
step "On Username, enable username sign-up and sign-in."
step "On Password, enable Sign-up with password and Add password to account."
step "Open SSO connections. Disable every social sign-in method."
pause "Continue when email, username, and password are enabled and social sign-in is disabled."

stage "Clerk development restriction" 2
say "Block public sign-up."
open_url "https://dashboard.clerk.com/"
step "Open Protect, then Restrictions. Enable restricted mode."
note "Restricted mode blocks public sign-up. Keep the email, username, and password sign-up methods enabled."
warn "Do not enable Public or Waitlist mode."
pause "Continue when the development instance is restricted."

stage "Predefined development user" 4
say "Create the only account that can use the local app."
open_url "https://dashboard.clerk.com/"
step "Confirm that the top of the dashboard says Development."
step "Open Users, then select Create user."
step "Enter your email, username, and a strong unique password."
step "Keep Ignore password policies clear, then select Create user."
step "Open the new user and copy its ID. The value starts with user_."
ask ALLOWED_CLERK_USER_ID "Paste the development user ID:"
while [[ ! "$ALLOWED_CLERK_USER_ID" =~ ^user_ ]]; do
  warn "The user ID must start with user_."
  ask ALLOWED_CLERK_USER_ID "Paste the development user ID:"
done

stage "Local environment" 4
say "Copy the Clerk development keys to the ignored local environment file."
open_url "https://dashboard.clerk.com/"
step "Open Configure, then Developers, then API keys."
step "Copy the Publishable Key. It starts with pk_test_."
ask NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the development Publishable Key:"
while [[ ! "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" =~ ^pk_test_ ]]; do
  warn "The development Publishable Key must start with pk_test_."
  ask NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the development Publishable Key:"
done
step "Reveal and copy the Secret Key. It starts with sk_test_."
ask_secret CLERK_SECRET_KEY "Paste the development Secret Key:"
while [[ ! "$CLERK_SECRET_KEY" =~ ^sk_test_ ]]; do
  warn "The development Secret Key must start with sk_test_."
  ask_secret CLERK_SECRET_KEY "Paste the development Secret Key:"
done
ask DATABASE_URL "Enter the local Postgres URL, or press Enter for the documented default:"
if [[ -z "$DATABASE_URL" ]]; then
  DATABASE_URL="postgresql://postgres:postgres@localhost:5432/doubtfire"
fi
write_env DATABASE_URL "$DATABASE_URL"
write_env NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
write_env CLERK_SECRET_KEY "$CLERK_SECRET_KEY"
write_env ALLOWED_CLERK_USER_ID "$ALLOWED_CLERK_USER_ID"
write_env NEXT_PUBLIC_CLERK_SIGN_IN_URL "/sign-in"
write_env NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL "/"
note "The file is ignored by Git. Do not commit it."

stage "Local test" 5
say "Test the development instance before you create production services."

if ! command -v docker >/dev/null 2>&1; then
  warn "Docker is not installed. Install Docker Desktop or Docker CLI with Colima, then run this wizard again."
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  if command -v colima >/dev/null 2>&1; then
    say "Docker is not running. The wizard will start Colima. The first start can take several minutes."
    colima start
  else
    step "Start Docker Desktop."
    pause "Continue when Docker Desktop is ready."
  fi
fi

if ! docker info >/dev/null 2>&1; then
  warn "Docker is still not ready. Start its runtime, then run this wizard again."
  exit 1
fi

COMPOSE_COMMAND=()
if docker compose version >/dev/null 2>&1; then
  COMPOSE_COMMAND=(docker compose)
elif command -v docker-compose >/dev/null 2>&1; then
  COMPOSE_COMMAND=(docker-compose)
else
  warn "Docker Compose is not installed. Install the Docker Compose plugin or docker-compose, then run this wizard again."
  exit 1
fi

if ! command -v pnpm >/dev/null 2>&1; then
  warn "pnpm is not installed. Enable Corepack or install pnpm 10.33.0, then run this wizard again."
  exit 1
fi

say "Start the included local Postgres service."
"${COMPOSE_COMMAND[@]}" up -d postgres
say "Install the pinned packages."
pnpm install --frozen-lockfile
say "Apply the database migrations."
pnpm db:migrate
step "In another terminal, run: pnpm dev"
step "Open http://localhost:3000 and sign in with the predefined account."
step "Also open http://localhost:3000/robots.txt. It must contain Disallow: /."
open_url "http://localhost:3000"
pause "Continue when local sign-in works."

stage "Railway services and regions" 5
say "Create the persistent app service and its database."
open_url "https://railway.com/new"
step "Select Deploy from GitHub repo and choose noobieoffrails/doubtfire."
step "Use main as the deployment branch. Railway will use the root Dockerfile."
step "On the project canvas, select + New, then Database, then PostgreSQL."
warn "Railway can show a failed first deployment before the required variables exist. Continue this setup before you diagnose it."
step "Open Settings for the app service. Select EU West."
step "Open Settings for Postgres. Select EU West and wait until Postgres is healthy."
pause "Continue when both services exist in EU West and Postgres is healthy."

stage "Railway database reference" 3
say "Give the app service access to Postgres."
open_url "https://railway.com/dashboard"
step "Open the app service, not Postgres. Open its Variables tab."
step "Select New Variable and enter these two fields:"
note "Name: DATABASE_URL"
note 'Value: ${{Postgres.DATABASE_URL}}'
note "If the database has another name, use Railway autocomplete to select its DATABASE_URL."
warn "Do not use the purple Add a Variable Reference help link. It opens the documentation."
pause "Continue when the app service has the DATABASE_URL reference."

stage "First Railway deployment" 5
say "Use the development Clerk values for one temporary deployment."
warn "This is only for setup. You will replace these values with production keys later."
step "In the app service Variables tab, add the following values from .env.local:"
note "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
note "CLERK_SECRET_KEY"
note "ALLOWED_CLERK_USER_ID"
step "Also add these fixed values:"
note "NEXT_PUBLIC_CLERK_SIGN_IN_URL = /sign-in"
note "NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL = /"
step "Dismiss the suggested DOUBTFIRE_ALLOW_UNAUTHENTICATED_PREVIEW variable. Do not add it to Railway."
step "Open Settings. Keep main connected and keep automatic deployments enabled."
step "Enable Wait for CI."
step "Review and deploy the staged changes. Wait for the migration, deployment, and /health check to succeed."
note "A warning about Clerk development keys is expected during this temporary deployment."
pause "Continue when Railway shows a healthy deployment."

stage "Railway custom domain" 3
ask APP_HOSTNAME "Enter the full app hostname, for example doubtfire.example.com:"
open_url "https://railway.com/dashboard"
step "Open the app service, then Settings, then Public Networking."
step "Select + Custom Domain and enter $APP_HOSTNAME."
step "Do not generate a Railway domain. Do not enable TCP Proxy or Outbound IPv6."
step "Keep the CNAME and TXT values from Railway visible. Both are required."
pause "Continue when Railway shows the CNAME and TXT values."

stage "Cloudflare app records" 4
say "Connect the public app hostname to Railway."
open_url "https://dash.cloudflare.com/"
step "Open your domain, then DNS, then Records."
step "Add the Railway CNAME and TXT records exactly as Railway shows them."
step "For the app CNAME, enable Proxy status so that the cloud is orange."
step "Open SSL/TLS, then Overview. Set the encryption mode to Full, not Full (Strict)."
warn "Do not create a Cache Everything rule for this authenticated app."
step "Return to Railway and wait for the custom domain to show a green check."
pause "Continue when https://$APP_HOSTNAME opens."

stage "Clerk production instance" 3
say "Create and restrict the production identity service."
open_url "https://dashboard.clerk.com/"
step "Use the Development selector in the top-left. Select Create production instance."
step "Clone the development settings. Enter $APP_HOSTNAME as the application domain."
step "If Clerk asks how to scope this subdomain, select Secondary application."
step "Confirm that the top-left instance selector now says Production."
step "Open Configure, then Protect, then Restrictions. Confirm that restricted mode is enabled."
pause "Continue when the production instance exists and restricted mode is enabled."

stage "Clerk production domain" 5
say "Authorize Clerk's production DNS records and certificates."
open_url "https://dashboard.clerk.com/"
step "Return to Overview. Select Continue setup, then Connect under Add DNS records."
step "On Domains, select Configure automatically."
step "In Cloudflare, review the five Clerk CNAME records. Confirm that each record says DNS only."
step "Authorize the one-time DNS change, then return to Clerk."
warn "The Railway app record stays orange. Only Clerk records must be gray."
step "Wait for DNS to show Verified and for both SSL certificates to finish."
step "If Clerk shows a Deploy certificates button, select it."
pause "Continue when DNS is verified and both Clerk certificates are ready."

stage "Predefined production user" 3
say "Create the only account that can use the production app."
open_url "https://dashboard.clerk.com/"
step "Confirm that the top-left instance selector says Production."
step "Open Users, select Create user, and enter your email, username, and a strong unique password."
step "Keep Ignore password policies clear, then select Create user."
step "Copy the production user ID. It starts with user_."
pause "Continue when the production instance and user are ready."

stage "Production keys in Railway" 4
say "Replace every temporary Clerk value in Railway."
open_url "https://dashboard.clerk.com/"
step "Confirm that the dashboard says Production. Open Configure, then Developers, then API keys."
step "Open Railway in another tab and select the app service Variables tab."
step "Replace NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY with the pk_live_ value."
step "Replace CLERK_SECRET_KEY with the sk_live_ value."
step "Replace ALLOWED_CLERK_USER_ID with the production user ID."
step "Seal CLERK_SECRET_KEY from its three-dot menu."
step "Review and deploy the staged changes. Wait for the health check to succeed."
warn "Do not put production keys in .env.local or GitHub Actions."
pause "Continue when production sign-in works at https://$APP_HOSTNAME."

stage "GitHub protection" 2
say "Require reviewed and verified changes for main."
open_url "https://github.com/noobieoffrails/doubtfire/settings/rules"
step "Select Rulesets, New ruleset, then New branch ruleset."
step "Name it Protect main, set enforcement to Active, and target the default branch."
step "Require a pull request and require the Verify status check to pass."
step "Keep branch deletion and force pushes blocked. Create the ruleset."
pause "Continue when the Protect main ruleset is active."

stage "Final deployment checks" 2
say "Now verify the deployment."
step "Open / while signed out. It must redirect to /sign-in."
step "Confirm that the Clerk Users page contains only the predefined account."
step "Open /robots.txt. It must contain User-agent: * and Disallow: /."
step "Run: curl -I https://$APP_HOSTNAME"
step "Confirm that X-Robots-Tag contains noindex and nofollow."
step "Open /health. It must return {\"status\":\"ok\"}."
step "Install the app on the iPhone. Confirm that it opens from the home screen and can sign in."
note "Android tablet acceptance is deferred for the initial release."
note "After seven days, record whether the repeat sign-in experience is acceptable on the iPhone."
warn "Phase 1 acceptance stays open until the seven-day iPhone check is complete."
note "Clerk and the selected language use necessary cookies. No analytics or advertising cookies exist."
note "If optional analytics or tracking is added later, add consent before that storage starts."
pause "Continue when the immediate production checks are complete."

finish
