#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=10
TOTAL_MINUTES=55
ENV_FILE="${DOUBTFIRE_ENV_FILE:-.env.local}"

banner "Doubtfire private deployment"

stage "Clerk development application" 6
say "Create the Clerk application that you will use for local development."
open_url "https://dashboard.clerk.com/apps/new"
step "Create an application named Doubtfire."
step "Open User & authentication. Require an email address and enable Password."
step "Disable social sign-in methods. This app uses one email and password."
step "Open Restrictions. Enable restricted mode and select Save."
warn "Do not enable Public or Waitlist mode."
pause "Continue when the development instance is restricted."

stage "Predefined development user" 5
say "Create the only account that can use the local app."
open_url "https://dashboard.clerk.com/"
step "Confirm that the top of the dashboard says Development."
step "Open Users, select Create user, and enter your email and a strong unique password."
step "Open the new user and copy its ID. The value starts with user_."
ask ALLOWED_CLERK_USER_ID "Paste the development user ID:"
while [[ ! "$ALLOWED_CLERK_USER_ID" =~ ^user_ ]]; do
  warn "The user ID must start with user_."
  ask ALLOWED_CLERK_USER_ID "Paste the development user ID:"
done

stage "Local environment" 5
say "Copy the Clerk development keys to the ignored local environment file."
open_url "https://dashboard.clerk.com/"
step "Open API keys. Copy the Publishable Key. It starts with pk_test_."
ask NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the development Publishable Key:"
while [[ ! "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" =~ ^pk_test_ ]]; do
  warn "The development Publishable Key must start with pk_test_."
  ask NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "Paste the development Publishable Key:"
done
step "Reveal and copy the Secret Key. It starts with sk_test_."
ask_secret CLERK_SECRET_KEY "Paste the development Secret Key:"
while [[ ! "$CLERK_SECRET_KEY" =~ ^sk_test_ ]]; do
  warn "The development Secret Key must start with sk_test_."
  ask_secret CLERK_SECRET_KEY "Paste the development Secret Key:"
done
ask DATABASE_URL "Enter the local Postgres URL, or press Enter for the documented default:"
if [[ -z "$DATABASE_URL" ]]; then
  DATABASE_URL="postgresql://postgres:postgres@localhost:5432/doubtfire"
fi
write_env DATABASE_URL "$DATABASE_URL"
write_env NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
write_env CLERK_SECRET_KEY "$CLERK_SECRET_KEY"
write_env ALLOWED_CLERK_USER_ID "$ALLOWED_CLERK_USER_ID"
write_env NEXT_PUBLIC_CLERK_SIGN_IN_URL "/sign-in"
write_env NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL "/"
note "The file is ignored by Git. Do not commit it."

stage "Local test" 5
say "Test the development instance before you create production services."
step "Start the included local Postgres service: docker compose up -d postgres"
step "In another terminal, run: pnpm install --frozen-lockfile"
step "Run: pnpm db:migrate"
step "Run: pnpm dev"
step "Open http://localhost:3000 and sign in with the predefined account."
step "Also open http://localhost:3000/robots.txt. It must contain Disallow: /."
open_url "http://localhost:3000"
pause "Continue when local sign-in works."

stage "Railway project and Postgres" 7
say "Create the persistent app service and its database."
open_url "https://railway.com/new"
step "Select Deploy from GitHub repo and choose noobieoffrails/doubtfire."
step "Use main as the deployment branch. Railway will use the root Dockerfile."
step "On the project canvas, select + New, then Database, then PostgreSQL."
step "Open the app service Variables tab and add this reference variable:"
note 'DATABASE_URL = ${{Postgres.DATABASE_URL}}'
note "If your database service has another name, select its DATABASE_URL from Railway autocomplete."
pause "Continue when the app and Postgres services exist."

stage "First Railway deployment" 6
say "Use the development Clerk values for one temporary deployment."
warn "This is only for setup. You will replace these values with production keys later."
step "In the app service Variables tab, add the following values from .env.local:"
note "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
note "CLERK_SECRET_KEY"
note "ALLOWED_CLERK_USER_ID"
step "Also add these fixed values:"
note "NEXT_PUBLIC_CLERK_SIGN_IN_URL = /sign-in"
note "NEXT_PUBLIC_CLERK_SIGN_IN_FALLBACK_REDIRECT_URL = /"
step "Open Settings and enable Wait for CI."
step "Deploy main. Wait for the migration, deployment, and /health check to succeed."
pause "Continue when Railway shows a healthy deployment."

stage "Custom domain and Cloudflare" 7
ask APP_HOSTNAME "Enter the full app hostname, for example doubtfire.example.com:"
open_url "https://railway.com/dashboard"
step "Open the app service, then Settings, then Public Networking."
step "Select + Custom Domain and enter $APP_HOSTNAME."
step "Keep the CNAME and TXT values from Railway visible. Both are required."
open_url "https://dash.cloudflare.com/"
step "Open your domain, then DNS, then Records."
step "Add the Railway CNAME and TXT records exactly as Railway shows them."
step "For the app CNAME, enable Proxy status so that the cloud is orange."
step "Open SSL/TLS, then Overview. Set the encryption mode to Full, not Full (Strict)."
warn "Do not create a Cache Everything rule for this authenticated app."
step "Return to Railway and wait for the custom domain to show a green check."
pause "Continue when https://$APP_HOSTNAME opens."

stage "Clerk production instance" 8
say "Create the production identity service and its one production user."
open_url "https://dashboard.clerk.com/"
step "Use the Development selector at the top. Select Create production instance."
step "Clone the development settings. Enter $APP_HOSTNAME as the application domain."
step "If Clerk asks how to scope this subdomain, select Secondary application."
step "Open Restrictions in Production. Confirm that restricted mode is enabled."
step "Open Domains. Add every DNS record that Clerk shows to Cloudflare."
step "Set each Clerk DNS record to DNS only. The cloud must be gray."
warn "The Railway app record stays orange. Only Clerk records must be gray."
step "When Clerk confirms DNS, select Deploy certificates."
step "In the Production instance, open Users and create your one user again."
step "Copy the production user ID. It starts with user_."
pause "Continue when the production instance and user are ready."

stage "Production keys in Railway" 4
say "Replace every temporary Clerk value in Railway."
open_url "https://dashboard.clerk.com/"
step "Confirm that the dashboard says Production. Open API keys."
step "Open Railway in another tab and select the app service Variables tab."
step "Replace NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY with the pk_live_ value."
step "Replace CLERK_SECRET_KEY with the sk_live_ value."
step "Replace ALLOWED_CLERK_USER_ID with the production user ID."
step "Seal CLERK_SECRET_KEY from its three-dot menu."
step "Redeploy and wait for the health check to succeed."
warn "Do not put production keys in .env.local or GitHub Actions."
pause "Continue when production sign-in works at https://$APP_HOSTNAME."

stage "GitHub protection and final checks" 2
open_url "https://github.com/noobieoffrails/doubtfire/settings/rules"
step "Select Rulesets, New ruleset, then New branch ruleset."
step "Name it Protect main, set enforcement to Active, and target the default branch."
step "Require a pull request and require the Verify status check to pass."
step "Keep branch deletion and force pushes blocked. Create the ruleset."
say "Now verify the deployment."
step "Open / while signed out. It must redirect to /sign-in."
step "Confirm that the Clerk Users page contains only the predefined account."
step "Open /robots.txt. It must contain User-agent: * and Disallow: /."
step "Run: curl -I https://$APP_HOSTNAME"
step "Confirm that X-Robots-Tag contains noindex and nofollow."
step "Open /health. It must return {\"status\":\"ok\"}."
step "Install the app on the tablet and phone. Confirm that both stay signed in for seven days."
note "Clerk and the selected language use necessary cookies. No analytics or advertising cookies exist."
note "If optional analytics or tracking is added later, add consent before that storage starts."

finish
